print "THE K NETWORK"
print "******************************"
print "In order to clear out your tables"
print "and start with default Schools and Users,"
print "run manage.py flush. Choose yes, then no."
print ""
print "Otherwise, you can run manage.py syncdb to"
print "restore default Schools and users."
print ""
print "Default Users (all passwords are 'password'"
print "ADMIN LOGINS: admin, pkuperman, mjoshen, ccoy"
print "TEACHER ACCOUNTS: teacher1, teacher2"
print "STUDENT ACCOUNTS: bsmith, cjones"
print "******************************"
print ""
print ""