print "THE K NETWORK"
print "******************************"
print "ATTENTION: If this is your first time running,"
print "    take a moment to run:"
print "    manage.py syncdb"
print "since that will give you the default Schools and Users"
print ""
print "Default Users (all passwords are 'password'"
print "    ADMIN LOGINS: admin, pkuperman, mjoshen, ccoy"
print "    TEACHER ACCOUNTS: teacher1, teacher2"
print "    STUDENT ACCOUNTS: bsmith, cjones"
print "******************************"
print ""
print ""